-- SQLBook: Code
CREATE TABLE beers (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  type varchar(255) NOT NULL,
  tagline varchar(255) NOT NULL,
  first_brewed varchar(255) NOT NULL,
  description LONGTEXT NOT NULL,
  image_url varchar(255) NOT NULL,  
  price_per_liter INT NOT NULL,
  abv INT NOT NULL,
  ph INT
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Braun','Buzz','A Real Bitter Experience.','09/2007','A light, crisp and bitter IPA brewed with English and American hops. A small batch brewed only once.','https://images.punkapi.com/v2/keg.png',4.5,4.4,9.7);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Black','Trashy Blonde','You Know You Shouldn''t','04/2008','A titillating, neurotic, peroxide punk of a Pale Ale. Combining attitude, style, substance, and a little bit of low self esteem for good measure; what would your mother say? The seductive lure of the sassy passion fruit hop proves too much to resist. All that is even before we get onto the fact that there are no additives, preservatives, pasteurization or strings attached. All wrapped up with the customary BrewDog bite and imaginative twist.','https://images.punkapi.com/v2/2.png',4.1,4.4,10);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Black','Berliner Weisse With Yuzu - B-Sides','Japanese Citrus Berliner Weisse.','11/2015','Japanese citrus fruit intensifies the sour nature of this German classic.','https://images.punkapi.com/v2/keg.png',4.2,3.2,12.6);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('IPA','Pilsen Lager','Unleash the Yeast Series.','09/2013','Our Unleash the Yeast series was an epic experiment into the differences in aroma and flavour provided by switching up your yeast. We brewed up a wort with a light caramel note and some toasty biscuit flavour, and hopped it with Amarillo and Centennial for a citrusy bitterness. Everything else is down to the yeast. Pilsner yeast ferments with no fruity esters or spicy phenols, although it can add a hint of butterscotch.','https://images.punkapi.com/v2/4.png',6.3,4.4,7.3);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Abbey','Avery Brown Dredge','Bloggers'' Imperial Pilsner.','02/2011','An Imperial Pilsner in collaboration with beer writers. Tradition. Homage. Revolution. We wanted to showcase the awesome backbone of the Czech brewing tradition, the noble Saaz hop, and also tip our hats to the modern beers that rock our world, and the people who make them.','https://images.punkapi.com/v2/5.png',7.2,4.4,8.5);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('IPA','Electric India','Vibrant Hoppy Saison.','05/2013','Re-brewed as a spring seasonal, this beer – which appeared originally as an Equity Punk shareholder creation – retains its trademark spicy, fruity edge. A perfect blend of Belgian Saison and US IPA, crushed peppercorns and heather honey are also added to produce a genuinely unique beer.','https://images.punkapi.com/v2/6.png',5.2,4.4,11.2);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Black','AB:12','Imperial Black Belgian Ale.','07/2012','An Imperial Black Belgian Ale aged in old Invergordon Scotch whisky barrels with mountains of raspberries, tayberries and blackberries in each cask. Decadent but light and dry, this beer would make a fantastic base for ageing on pretty much any dark fruit - we used raspberries, tayberries and blackberries beause they were local.','https://images.punkapi.com/v2/7.png',11.2,5.3,16);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('IPA','Fake Lager','Bohemian Pilsner.','03/2013','Fake is the new black. Fake is where it is at. Fake Art, fake brands, fake breasts, and fake lager. We want to play our part in the ugly fallout from the Lager Dream. Say hello to Fake Lager – a zesty, floral 21st century faux masterpiece with added BrewDog bitterness.','https://images.punkapi.com/v2/8.png',4.7,4.4,5.4);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('IPA','AB:07','Whisky Cask-Aged Scotch Ale.','03/2010','Whisky cask-aged imperial scotch ale. Beer perfect for when the rain is coming sideways. Liquorice, plum and raisin temper the warming alcohol, producing a beer capable of holding back the Scottish chill.','https://images.punkapi.com/v2/9.png',12.5,5.6,8.9);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('IPA','Bramling X','Single Hop IPA Series - 2011.','01/2011','Good old Bramling Cross is elegant, refined, assured, (boring) and understated. Understated that is unless you hop the living daylights out of a beer with it. This is Bramling Cross re-invented and re-imagined, and shows just what can be done with English hops if you use enough of them. Poor Bramling Cross normally gets lost in a woeful stream of conformist brown ales made by sleepy cask ale brewers. But not anymore. This beer shows that British hops do have some soul, and is a fruity riot of blackberries, pears, and plums. Reminds me of the bramble, apple and ginger jam my grandmother used to make.','https://images.punkapi.com/v2/10.png',7.5,4.4,9.9);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('IPA','Misspent Youth','Milk & Honey Scotch Ale.','04/2013','The brainchild of our small batch brewer, George Woods. A dangerously drinkable milk sugar- infused Scotch Ale.','https://images.punkapi.com/v2/keg.png',7.3,4.4,13.2);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Braun','Arcade Nation','Seasonal Black IPA.','12/2015','Running the knife-edge between an India Pale Ale and a Stout, this particular style is one we truly love. Black IPAs are a great showcase for the skill of our brew team, balancing so many complex and twisting flavours in the same moment. The citrus, mango and pine from the hops – three of our all-time favourites – play off against the roasty dryness from the malt bill at each and every turn.','https://images.punkapi.com/v2/12.png',5.3,4.2,12.5);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Braun','Movember','Moustache-Worthy Beer.','11/2009','A deliciously robust, black malted beer with a decadent dark, dry cocoa flavour that provides an enticing backdrop to the Cascade hops.','https://images.punkapi.com/v2/13.png',4.5,5.2,9.6);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Black','Alpha Dog','Existential Red Ale.','02/2010','A fusion of caramel malt flavours and punchy New Zealand hops. A session beer you can get your teeth into.','https://images.punkapi.com/v2/14.png',4.5,4.4,12.6);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Abbey','Mixtape 8','An Epic Fusion Of Old Belgian, American New Wave, And Scotch Whisky.','01/2012','This recipe is for the Belgian Tripel base. A blend of two huge oak aged beers – half a hopped up Belgian Tripel, and half a Triple India Pale Ale. Both aged in single grain whisky barrels for two years and blended, each beer brings its own character to the mix. The Belgian Tripel comes loaded with complex spicy, fruity esters, and punchy citrus hop character.','https://images.punkapi.com/v2/15.png',14.5,4.4,11.4);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Blonde','Libertine Porter','Dry-Hopped Aggressive Porter.','01/2012','An avalanche of cross-continental hop varieties give this porter a complex spicy, resinous and citrusy aroma, with a huge malt bill providing a complex roasty counterpoint. Digging deeper into the flavour draws out cinder toffee, bitter chocolate and hints of woodsmoke.','https://images.punkapi.com/v2/16.png',6.1,4.4,7.8);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Blonde','AB:06','Imperial Black IPA.','04/2011','Our sixth Abstrakt, this imperial black IPA combined dark malts with a monumental triple dry-hop, using an all-star team of some of our favourite American hops. Roasty and resinous.','https://images.punkapi.com/v2/17.png',11.2,NULL,6.9);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Black','Russian Doll – India Pale Ale','Nesting Hop Bomb.','08/2014','The levels of hops vary throughout the range. We love hops, so all four beers are big, bitter badasses, but by tweaking the amount of each hop used later in the boil and during dry- hopping, we can balance the malty backbone with some unexpected flavours. Simcoe is used in the whirlpool for all four beers, and yet still lends different characters to each','https://images.punkapi.com/v2/18.png',6,5.2,10.3);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Abbey','Hello My Name Is Mette-Marit','Lingonberry Double IPA.','06/2013','We sent this beer to Norway where it was known as ''Hello, my name is Censored’. You can make up your own mind as to why. This brew was a red berry explosion, with a reisnous bitter edge layered with dry berry tartness.','https://images.punkapi.com/v2/19.png',8.2,4.4,12.7);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Black','Rabiator','Imperial Wheat Beer','03/2011','Imperial Wheat beer / Weizenbock brewed by a homesick German in leather trousers. Think banana bread, bubble gum and David Hasselhoff.','https://images.punkapi.com/v2/keg.png',10.27,4.4,10.6);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Abbey','Vice Bier','Hoppy Wheat Bier.','04/2013','Our take on the classic German Kristallweizen. A clear German wheat beer, layers of bubblegum and vanilla perfectly balanced with the American and New Zealand hops.','https://images.punkapi.com/v2/keg.png',4.3,4,12.5);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Abbey','Devine Rebel (w/ Mikkeller)','Oak-aged Barley Wine.','12/2008','Two of Europe''s most experimental, boundary-pushing brewers, BrewDog and Mikkeller, combined forces to produce a rebellious beer that combined their respective talents and brewing skills. The 12.5% Barley Wine fermented well, and the champagne yeast drew it ever closer to 12.5%. The beer was brewed with a single hop variety and was going to be partially aged in oak casks.','https://images.punkapi.com/v2/22.png',12.5,4.4,11.1);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Abbey','Storm','Islay Whisky Aged IPA.','12/2007','Dark and powerful Islay magic infuses this tropical sensation of an IPA. Using the original Punk IPA as a base, we boosted the ABV to 8% giving it some extra backbone to stand up to the peated smoke imported directly from Islay.','https://images.punkapi.com/v2/23.png',8,4.4,9.7);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('IPA','The End Of History','The World''s Strongest Beer.','06/2011','The End of History: The name derives from the famous work of philosopher Francis Fukuyama, this is to beer what democracy is to history. Complexity defined. Floral, grapefruit, caramel and cloves are intensified by boozy heat.','https://images.punkapi.com/v2/24.png',55,4.4,8.4);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Braun','Bad Pixie','Spiced Wheat Beer.','10/2008','2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.','https://images.punkapi.com/v2/25.png',4.7,4.4,7.9);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('IPA','Skull Candy','Pacific Hopped Amber Bitter.','02/2010','The first beer that we brewed on our newly commissioned 5000 litre brewhouse in Fraserburgh 2009. A beer with the malt and body of an English bitter, but the heart and soul of vibrant citrus US hops.','https://images.punkapi.com/v2/keg.png',3.5,4.4,11.2);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Braun','Dog B','Cacao, Coffee Chili Anniversary Stout.','05/2013','Our anniversary stout was based on AB:04, one of our most sought after beers ever. This beer is slightly different each year, with subtle variations coming into play purely down to environmental and fermentation factors. What doesn''t change is the rich dark chocolate, bitter coffee and chilli warmth of this monumental Stout.','https://images.punkapi.com/v2/27.png',15,4.4,8.9);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Braun','HBC 369','Single Hop India Pale Ale – 2012.','02/2012','HBC 369 brings rich fruity flavours with the tiniest layer of candy coating on top. HBC 369 (the hop) can bring notes of blueberries, pear, and possibly even sweet potato. HBC 369 (the beer) was balanced, with just one hop providing a complex aroma, and a dry bitterness.','https://images.punkapi.com/v2/28.png',6.7,4.4,10.8);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Blonde','10 Heads High','Imperial Red Ale.','04/2013','10 Heads High is loosely based on our awesome 2011 Prototype beer Hops Kill Nazis. This is an uncompromising 7.8% Imperial Red Ale loaded high with American Hops. Think of this as an Imperial India Red Ale, or a super-charged version of 5am Saint. Either way this is a seriously good beer!','https://images.punkapi.com/v2/29.png',7.8,4.4,10.9);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Abbey','Dana - IPA Is Dead','Single Hop India Pale Ale.','02/2013','Hailing from Slovenia, Dana was originally cross bred from the German Hallertau Magnum and native Slovenian varieties. Like any good faux noble hop should, it infuses a rustic, musty spiciness into a toasty beast of a malt base.','https://images.punkapi.com/v2/30.png',6.7,4.4,11.5);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Abbey','Nanny State','Alcohol Free Hoppy Ale.','08/2009','Brewing a full flavoured craft beer at 0.5% is no easy task. Packed with loads of Centennial, Amarillo, Columbus, Cascade and Simcoe hops, dry hopped to the brink and back and sitting at 55 IBUs, Nanny State is a force to be reckoned with. With a backbone of 8 different specialty malts, Nanny State will tantalise your taste buds and leave you yearning for more.','https://images.punkapi.com/v2/31.png',0.5,4.4,12.9);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Abbey','AB:05','Belgian Imperial Stout.','12/2010','Belgian Imperial Stout aged on toasted coconut and cacao. The Belgian yeast strain introduces a whole new dimension to the Imperial Stout style resulting in a beer that resembles a marshmallow toasted on a smouldering barbeque then smothered in dark chocolate. Massively seductive and encapsulating this blacker than midnight beer pours with coffee brown head so thick you could almost stand on it, and with an epic lacing on your glass.','https://images.punkapi.com/v2/32.png',12.5,4.4,14.5);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Blonde','Sorachi Ace','Single Hop IPA Series - 2011.','01/2011','A hop that tastes of bubble gum? Seriously? No, we did not believe it either. But it does! This is one unique, son of a bitch of a hop. Lemony, deep, musty with a smoothness that belies its power. This hop is lemony like a lemon who was angry earlier but is now tired because of all the rage. This hop of Japanese origin is best enjoyed trying to make sushi from your gold fish, or trying to persuade your girlfriend (or boyfriend maybe) to dress up as a Geisha for Valentine’s Day.','https://images.punkapi.com/v2/33.png',7.5,4.4,9.8);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('IPA','Bourbon Baby','Barrel-Aged Scotch Ale.','01/2014','Santa Paws Scotch ale aged in bourbon barrels - light, dry and toasty, with vanilla, hints of chocolate and ginger biscuit, and a faint spicy hoppiness.','https://images.punkapi.com/v2/34.png',5.8,4.4,11.5);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Blonde','Berliner Weisse With Raspberries And Rhubarb - B-Sides','Fruity Berliner Weisse.','11/2015','Tart, dry and acidic with a punch of summer berry as rhubarb crumble.','https://images.punkapi.com/v2/keg.png',3.6,3.2,13.1);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Abbey','Shipwrecker Circus (w/ Oskar Blues)','American Barley Wine - Oskar Blues Collab.','09/2013','In collaboration with the awesome Oskar Blues from Colorado, we created this big, twisted 10.5% American style barley wine. Big boozy aromas and a sweet viscosity, packed in with some heavy-hitting C-hops, for an intense bitterness to balance this full-bodied malt monster.','https://images.punkapi.com/v2/36.png',10.5,4.4,12.8);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Black','Zephyr','There’s A Storm Brewing.','10/2008','A 9.2% Double IPA aged for 21 months in a 1965 Invergordon cask with 30 kg of fresh highland strawberries. This beer is a riot of whisky, caramel and strawberry, all tempered by a toe curling bitterness enducing rapture in all who taste it. Who needs champagne?','https://images.punkapi.com/v2/37.png',12.5,4.4,9.9);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('IPA','Belgian Trappist','Unleash the Yeast Series.','09/2013','Our Unleash the Yeast series was an epic experiment into the differences in aroma and flavour provided by switching up your yeast. We brewed up a wort with a light caramel note and some toasty biscuit flavour, and hopped it with Amarillo and Centennial for a citrusy bitterness. Everything else is down to the yeast. Abbey style yeasts add distinctive spicy and fruity notes, and dry out the finished beer.','https://images.punkapi.com/v2/38.png',6.3,4.4,8.5);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Black','Kohatu - IPA Is Dead','Single Hop India Pale Ale.','02/2014','As you’d expect from a New Zealand hop variety, Kohatu contributes bags of tropical fruit, but with loads of lime notes, & pineapple hits. Seriously fruity, with sweet, juicy melon and stonefruit notes.','https://images.punkapi.com/v2/39.png',7.2,4.4,7.8);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Blonde','Hello My Name is Vladimir','Limonnik Infused Imperial IPA (Not for Gays).','01/2014','A Limonnik-infused, triple dry- hopped double IPA. Dry berry tartness and intense citrus hop character meld with a dry bready malt base, boosted by a hint of alcohol warmth. This beer was brewed as a protest against the anti-LGBT legislation in Russia surrounding the Sochi Olympics.','https://images.punkapi.com/v2/40.png',8.2,4.4,11.2);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Blonde','AB:17','Three Coffee Rye Imperial Porter.','10/2014','A triple whammy of coffee from HasBean gives our 17th Abstrakt concept beer an intense and roasty, dark mocha character. We brewed with espresso in the mash, cafetiere in the boil, and whole roast beans in the whirlpool and the fermenter.','https://images.punkapi.com/v2/41.png',10.7,4.3,10.6);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Blonde','Hardcore IPA','Explicit Imperial Ale. Citrusy. Resinous. Intense.','12/2009','Pounding a triple payload of the biggest North American hops humanity has devised, braced by a backbone of caramel malt, this beer is deep, astringent and resinous, pushing to the extremes of lupulin thresholds. There’s nothing inscrutable going on; no mystery in the backstory. It doesn’t seek to be understood. A beer incapable of empathy; only hop overload.','https://images.punkapi.com/v2/42.png',9.2,4.4,10.4);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Blonde','American Wheat','Hoppy American Wheat.','07/2014','A luscious blend of peach, blood orange and banana to make a suitably refreshing beverage that happily straddles the Atlantic.','https://images.punkapi.com/v2/keg.png',4.5,5.3,11.1);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('IPA','Dog Wired (w/8 Wired)','New Zealand Imperial Pilsner.','06/2013','Brewed in collaboration with Soren from New Zealand’s stellar 8-Wired brewery, this is an Imperial Pilsner featuring two of our favourite New Zealand hops: Nelson Sauvin and Motueka. Sitting at a dangerously drinkable 7.1% ABV there’s a touch of Munich malt which gives this beer that little extra caramel biscuit bite to compliment the lip smackingly tropical hops. Expect an all out NZ hoppy riot.','https://images.punkapi.com/v2/44.png',7.1,4.4,9.7);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Abbey','The Physics','Laid Back Amber Beer.','04/2007','A hoppy Amber Ale that won World''s Best Amber Beer in the World Beer Awards 2007. Malt and hops are in perfect harmony in this incredibly balanced beer. Biscuity, bitter and packing a surprisingly hoppy punch, this beer ultimately morphed into 5AM Saint.','https://images.punkapi.com/v2/45.png',5,4.4,10.8);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('IPA','Anarchist Alchemist','Triple Hopped Triple Ipa.','03/2012','About as far as you can push an IPA; Anarchist Alchemist packs in three times the malt and three of our favourite hops. Nelson Sauvin, Amarillo and Centennial bring a range of flavours, touching on tropical fruit, white grape, tangerine, grapefruit, pine, spiced orange... the list goes on!','https://images.punkapi.com/v2/46.png',16.5,4.4,10.9);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('IPA','AB:15','Salted Caramel Popcorn Strong Ale.','03/2013','A salted caramel popcorn Imperial Ale. Bourbon and Rum barrel aged, this 12.8% ale has complex and twisting flavours. Bitter caramel, wood, smoke, spice, treacle and vanilla are all present and intertwine against a smooth and lightly chewy mouthfeel. The salted caramel popcorn lends subtle hints of a smoky brininess.','https://images.punkapi.com/v2/47.png',12.8,4.4,12.4);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('IPA','Goldings - IPA Is Dead','Single Hop India Pale Ale.','02/2013','This is East Kent Goldings re- invented and re-imagined and shows just what can be done with English hops if you use enough of them. In this amped up Goldings reincarnation expect to be slammed with floral lavender, a fruity riot of blackberries and spiced pears, bubblegum, plums and the illusion of thyme.','https://images.punkapi.com/v2/48.png',6.7,4.4,8.4);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Black','AB:14','Oak-Aged Imperial Weizenbock.','02/2013','Think banoffee pie; loads of creamy sweet banana, and sticky warm toffee. This beer is super complex, and one for the sweet-toothed!','https://images.punkapi.com/v2/49.png',10,4.4,9.4);
INSERT INTO beers(type,name,tagline,first_brewed,description,image_url,abv,ph,price_per_liter) VALUES ('Black','Lost Dog (w/Lost Abbey)','Rum-Aged Imperial Porter - Lost Abbey Collab.','11/2011','Our first beer aged in rum casks, Lost Dog saw us brew a collaboration imperial porter with our friends at Lost Abbey. The base beer was packed with toffee, chocolate and roasty notes, balanced with a subtle spicy hop character. The rum casks add a warming, spiced vanilla edge.','https://images.punkapi.com/v2/50.png',10,4.4,7.6);
